name: Publish Resume
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: |
            front-end-resume.tex
            mechatronics-resume.tex
            product-design-resume.tex
          latexmk_use_lualatex: true
          latexmk_shell_escape: true
          extra_fonts: |
            ./assets/fonts/*.tff
            ./assets/fonts/*.otf
      - name: Publish PDFs to Portfolio
        uses: nkoppel/push-files-to-another-repository@v1.1.1
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-files: ./*.pdf
          destination-username: Bumbleboss
          destination-repository: bumbleboss.xyz
          destination-branch: pdf-copy
          destination-directory: public/files/
          commit-email: me@bumbleboss.xyz
          commit-message: 'chore: updated new resumes'