name: Publish resume
on:
  push:
    branches:
      - 'master'
jobs:
  publish_latex_resume:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Compile LaTeX documents
        uses: xu-cheng/latex-action@v3
        with:
          root_file: |
            front-end_engineer_resume.tex
            mechatronics_engineer_resume.tex
            product_designer_resume.tex
          latexmk_use_lualatex: true
          latexmk_shell_escape: true
          extra_fonts: |
            ./assets/fonts/*.tff
            ./assets/fonts/*.otf

      - name: Copy PDFs to out directory
        run: mkdir out && cp *.pdf out

      - name: Publish resumes to portfolio
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: out
          destination-github-username: Bumbleboss
          destination-repository-name: bumbleboss.xyz
          target-branch: master
          target-directory: public/files/
          user-name: 'Mohsen M.'
          user-email: me@bumbleboss.xyz
          commit-message: 'chore: automated resume update via GH actions'