name: Resume Build Test
on:
  push:
    branches:
      - '*'
      - '!master'
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Compile LaTeX documents
        uses: xu-cheng/latex-action@v3
        with:
          root_file: |
            engineer_mechatronics.tex
            engineer_ui_design.tex
            engineer_ui_frontend.tex
          latexmk_use_lualatex: true
          latexmk_shell_escape: true
          extra_fonts: |
            ./assets/fonts/*.tff
            ./assets/fonts/*.otf